// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'copyUrl': string;
  'shareButton': string;
}
export const cssExports: CssExports;
export default cssExports;
