// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'badge': string;
  'container': string;
  'inactive': string;
  'languagesCount': string;
  'nextButton': string;
  'paginationActive': string;
  'paginationButtons': string;
  'paginationDisabled': string;
  'previousButton': string;
  'snippet': string;
  'snippetContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
